configurations {
    liquibaseRuntime.extendsFrom sourceSets.main.compileClasspath
}

dependencies {
  implementation "org.liquibase:liquibase-core"
  liquibaseRuntime "org.liquibase:liquibase-core"
  // Dependency required to parse options. Refer to https://github.com/liquibase/liquibase-gradle-plugin/tree/Release_2.2.0#news.
  liquibaseRuntime "info.picocli:picocli:4.7.6"
  liquibaseRuntime "com.mysql:mysql-connector-j"
  liquibaseRuntime "org.liquibase.ext:liquibase-hibernate6:${dependencyManagement.importedProperties['liquibase.version']}"
  // jhipster-needle-gradle-dependency - JHipster will add additional dependencies here
}

project.ext.diffChangelogFile = "src/main/resources/config/liquibase/changelog/" + new Date().format("yyyyMMddHHmmss") + "_changelog.xml"
if (!project.hasProperty("runList")) {
 project.ext.runList = "main"
}

liquibase {
  activities {
    main {
      driver "com.mysql.cj.jdbc.Driver"
      url "jdbc:mysql://localhost:3306/Strip"
      username "root"
      password "Delete123."
      changelogFile "src/main/resources/config/liquibase/master.xml"
      logLevel "debug"
      classpath "src/main/resources/"
    }
    diffLog {
      driver "com.mysql.cj.jdbc.Driver"
      url "jdbc:mysql://localhost:3306/Strip"
      username "root"
      password "Delete123."
      changelogFile project.ext.diffChangelogFile
      referenceUrl "hibernate:spring:strip.domain?dialect=org.hibernate.dialect.MySQL8Dialect&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
      logLevel "debug"
      classpath "$buildDir/classes/java/main"
    }
  // activities {
  //   main {
  //     driver "com.mysql.cj.jdbc.Driver"
  //     url "jdbc:mysql://hopper.proxy.rlwy.net:56096/railway?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true"
  //     username "root"
  //     password "OWtcyLFmZslmDrGeCvtvrnioIBuhQSTT"
  //     changelogFile "src/main/resources/config/liquibase/master.xml"
  //     logLevel "debug"
  //     classpath "src/main/resources/"
  //   }
  //   diffLog {
  //     driver "com.mysql.cj.jdbc.Driver"
  //     referenceDriver "liquibase.ext.hibernate.database.connection.HibernateDriver"
  //     url "jdbc:mysql://hopper.proxy.rlwy.net:56096/railway?useUnicode=true&characterEncoding=utf8&useSSL=false"
  //     username "root"
  //     password "OWtcyLFmZslmDrGeCvtvrnioIBuhQSTT"
  //     changelogFile project.ext.diffChangelogFile
  //     referenceUrl "hibernate:spring:strip.domain?dialect=org.hibernate.dialect.MySQL8Dialect&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
  //     logLevel "debug"
  //     classpath "$buildDir/classes/java/main"
  //   }
  }
  runList = project.ext.runList
}

liquibaseDiff.dependsOn compileJava
liquibaseDiffChangelog.dependsOn compileJava

ext {
  if (project.hasProperty("no-liquibase")) {
    springProfiles += ",no-liquibase"
  }
}
