export enum WalletTransactionType {
  DEPOSIT = 'DEPOSIT',

  WITHDRAW = 'WITHDRAW',

  REFUND = 'REFUND',

  DRIVER_CREATE_TRIP_FEE = 'DRIVER_CREATE_TRIP_FEE',

  DRRIVER_DONE_TRIP_REFUND = 'DRRIVER_DONE_TRIP_REFUND',

  DRIVER_DONE_TRIP_FEE = 'DRIVER_DONE_TRIP_FEE',

  PASSENGER_APPROVE_FEE = 'PASSENGER_APPROVE_FEE',
}
