package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DriverPackageSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionAllPropertiesEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertDriverPackageSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertDriverPackageSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionAllUpdatablePropertiesEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertDriverPackageSubscriptionUpdatableFieldsEquals(expected, actual);
        assertDriverPackageSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionAutoGeneratedPropertiesEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertThat(expected)
            .as("Verify DriverPackageSubscription auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionUpdatableFieldsEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertThat(expected)
            .as("Verify DriverPackageSubscription relevant properties")
            .satisfies(e -> assertThat(e.getPurchaseDate()).as("check purchaseDate").isEqualTo(actual.getPurchaseDate()))
            .satisfies(e -> assertThat(e.getExpirationDate()).as("check expirationDate").isEqualTo(actual.getExpirationDate()))
            .satisfies(e -> assertThat(e.getPackagePrice()).as("check packagePrice").isEqualTo(actual.getPackagePrice()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionUpdatableRelationshipsEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertThat(expected)
            .as("Verify DriverPackageSubscription relationships")
            .satisfies(e -> assertThat(e.getDriver()).as("check driver").isEqualTo(actual.getDriver()))
            .satisfies(e -> assertThat(e.getPackageDriver()).as("check packageDriver").isEqualTo(actual.getPackageDriver()));
    }
}
