package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DriverPackageSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionAllPropertiesEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertDriverPackageSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertDriverPackageSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionAllUpdatablePropertiesEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertDriverPackageSubscriptionUpdatableFieldsEquals(expected, actual);
        assertDriverPackageSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionAutoGeneratedPropertiesEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertThat(actual)
            .as("Verify DriverPackageSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionUpdatableFieldsEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertThat(actual)
            .as("Verify DriverPackageSubscription relevant properties")
            .satisfies(a -> assertThat(a.getPurchaseDate()).as("check purchaseDate").isEqualTo(expected.getPurchaseDate()))
            .satisfies(a -> assertThat(a.getExpirationDate()).as("check expirationDate").isEqualTo(expected.getExpirationDate()))
            .satisfies(a -> assertThat(a.getPackagePrice()).as("check packagePrice").isEqualTo(expected.getPackagePrice()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPackageSubscriptionUpdatableRelationshipsEquals(
        DriverPackageSubscription expected,
        DriverPackageSubscription actual
    ) {
        assertThat(actual)
            .as("Verify DriverPackageSubscription relationships")
            .satisfies(a -> assertThat(a.getDriver()).as("check driver").isEqualTo(expected.getDriver()))
            .satisfies(a -> assertThat(a.getPackageDriver()).as("check packageDriver").isEqualTo(expected.getPackageDriver()));
    }
}
