package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DriverPointHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPointHistoryAllPropertiesEquals(DriverPointHistory expected, DriverPointHistory actual) {
        assertDriverPointHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertDriverPointHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPointHistoryAllUpdatablePropertiesEquals(DriverPointHistory expected, DriverPointHistory actual) {
        assertDriverPointHistoryUpdatableFieldsEquals(expected, actual);
        assertDriverPointHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPointHistoryAutoGeneratedPropertiesEquals(DriverPointHistory expected, DriverPointHistory actual) {
        assertThat(actual)
            .as("Verify DriverPointHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPointHistoryUpdatableFieldsEquals(DriverPointHistory expected, DriverPointHistory actual) {
        assertThat(actual)
            .as("Verify DriverPointHistory relevant properties")
            .satisfies(a -> assertThat(a.getPointId()).as("check pointId").isEqualTo(expected.getPointId()))
            .satisfies(a -> assertThat(a.getPoint()).as("check point").isEqualTo(expected.getPoint()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverPointHistoryUpdatableRelationshipsEquals(DriverPointHistory expected, DriverPointHistory actual) {
        assertThat(actual)
            .as("Verify DriverPointHistory relationships")
            .satisfies(a -> assertThat(a.getDriver()).as("check driver").isEqualTo(expected.getDriver()))
            .satisfies(a -> assertThat(a.getUserDetail()).as("check userDetail").isEqualTo(expected.getUserDetail()));
    }
}
