package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DriverAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverAllPropertiesEquals(Driver expected, Driver actual) {
        assertDriverAutoGeneratedPropertiesEquals(expected, actual);
        assertDriverAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverAllUpdatablePropertiesEquals(Driver expected, Driver actual) {
        assertDriverUpdatableFieldsEquals(expected, actual);
        assertDriverUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverAutoGeneratedPropertiesEquals(Driver expected, Driver actual) {
        assertThat(expected)
            .as("Verify Driver auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverUpdatableFieldsEquals(Driver expected, Driver actual) {
        assertThat(expected)
            .as("Verify Driver relevant properties")
            .satisfies(e -> assertThat(e.getDriverID()).as("check driverID").isEqualTo(actual.getDriverID()))
            .satisfies(e -> assertThat(e.getUsedtoDriver()).as("check usedtoDriver").isEqualTo(actual.getUsedtoDriver()))
            .satisfies(e -> assertThat(e.getExpirationDate()).as("check expirationDate").isEqualTo(actual.getExpirationDate()))
            .satisfies(e -> assertThat(e.getDriverStatus()).as("check driverStatus").isEqualTo(actual.getDriverStatus()))
            .satisfies(e -> assertThat(e.getDriverPoint()).as("check driverPoint").isEqualTo(actual.getDriverPoint()))
            .satisfies(e -> assertThat(e.getBannedDay()).as("check bannedDay").isEqualTo(actual.getBannedDay()))
            .satisfies(e -> assertThat(e.getDriverLicense()).as("check driverLicense").isEqualTo(actual.getDriverLicense()))
            .satisfies(
                e ->
                    assertThat(e.getDriverLicenseContentType())
                        .as("check driverLicense contenty type")
                        .isEqualTo(actual.getDriverLicenseContentType())
            )
            .satisfies(e -> assertThat(e.getIdentityCardFaceUp()).as("check identityCardFaceUp").isEqualTo(actual.getIdentityCardFaceUp()))
            .satisfies(
                e ->
                    assertThat(e.getIdentityCardFaceUpContentType())
                        .as("check identityCardFaceUp contenty type")
                        .isEqualTo(actual.getIdentityCardFaceUpContentType())
            )
            .satisfies(
                e -> assertThat(e.getIdentityCardFacedown()).as("check identityCardFacedown").isEqualTo(actual.getIdentityCardFacedown())
            )
            .satisfies(
                e ->
                    assertThat(e.getIdentityCardFacedownContentType())
                        .as("check identityCardFacedown contenty type")
                        .isEqualTo(actual.getIdentityCardFacedownContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverUpdatableRelationshipsEquals(Driver expected, Driver actual) {}
}
