package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DriverAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverAllPropertiesEquals(Driver expected, Driver actual) {
        assertDriverAutoGeneratedPropertiesEquals(expected, actual);
        assertDriverAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverAllUpdatablePropertiesEquals(Driver expected, Driver actual) {
        assertDriverUpdatableFieldsEquals(expected, actual);
        assertDriverUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverAutoGeneratedPropertiesEquals(Driver expected, Driver actual) {
        assertThat(actual)
            .as("Verify Driver auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverUpdatableFieldsEquals(Driver expected, Driver actual) {
        assertThat(actual)
            .as("Verify Driver relevant properties")
            .satisfies(a -> assertThat(a.getDriverID()).as("check driverID").isEqualTo(expected.getDriverID()))
            .satisfies(a -> assertThat(a.getUsedtoDriver()).as("check usedtoDriver").isEqualTo(expected.getUsedtoDriver()))
            .satisfies(a -> assertThat(a.getExpirationDate()).as("check expirationDate").isEqualTo(expected.getExpirationDate()))
            .satisfies(a -> assertThat(a.getDriverStatus()).as("check driverStatus").isEqualTo(expected.getDriverStatus()))
            .satisfies(a -> assertThat(a.getDriverPoint()).as("check driverPoint").isEqualTo(expected.getDriverPoint()))
            .satisfies(a -> assertThat(a.getBannedDay()).as("check bannedDay").isEqualTo(expected.getBannedDay()))
            .satisfies(a -> assertThat(a.getDriverLicense()).as("check driverLicense").isEqualTo(expected.getDriverLicense()))
            .satisfies(
                a ->
                    assertThat(a.getDriverLicenseContentType())
                        .as("check driverLicense contenty type")
                        .isEqualTo(expected.getDriverLicenseContentType())
            )
            .satisfies(
                a -> assertThat(a.getIdentityCardFaceUp()).as("check identityCardFaceUp").isEqualTo(expected.getIdentityCardFaceUp())
            )
            .satisfies(
                a ->
                    assertThat(a.getIdentityCardFaceUpContentType())
                        .as("check identityCardFaceUp contenty type")
                        .isEqualTo(expected.getIdentityCardFaceUpContentType())
            )
            .satisfies(
                a -> assertThat(a.getIdentityCardFacedown()).as("check identityCardFacedown").isEqualTo(expected.getIdentityCardFacedown())
            )
            .satisfies(
                a ->
                    assertThat(a.getIdentityCardFacedownContentType())
                        .as("check identityCardFacedown contenty type")
                        .isEqualTo(expected.getIdentityCardFacedownContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDriverUpdatableRelationshipsEquals(Driver expected, Driver actual) {
        // empty method
    }
}
