package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeedbackAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackAllPropertiesEquals(Feedback expected, Feedback actual) {
        assertFeedbackAutoGeneratedPropertiesEquals(expected, actual);
        assertFeedbackAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackAllUpdatablePropertiesEquals(Feedback expected, Feedback actual) {
        assertFeedbackUpdatableFieldsEquals(expected, actual);
        assertFeedbackUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackAutoGeneratedPropertiesEquals(Feedback expected, Feedback actual) {
        assertThat(actual)
            .as("Verify Feedback auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackUpdatableFieldsEquals(Feedback expected, Feedback actual) {
        assertThat(actual)
            .as("Verify Feedback relevant properties")
            .satisfies(a -> assertThat(a.getFeedbackID()).as("check feedbackID").isEqualTo(expected.getFeedbackID()))
            .satisfies(a -> assertThat(a.getFeedbackType()).as("check feedbackType").isEqualTo(expected.getFeedbackType()))
            .satisfies(
                a -> assertThat(a.getFeedbackDescription()).as("check feedbackDescription").isEqualTo(expected.getFeedbackDescription())
            )
            .satisfies(a -> assertThat(a.getFeedbackRating()).as("check feedbackRating").isEqualTo(expected.getFeedbackRating()))
            .satisfies(a -> assertThat(a.getFeedbackStatus()).as("check feedbackStatus").isEqualTo(expected.getFeedbackStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackUpdatableRelationshipsEquals(Feedback expected, Feedback actual) {
        assertThat(actual)
            .as("Verify Feedback relationships")
            .satisfies(a -> assertThat(a.getTrip()).as("check trip").isEqualTo(expected.getTrip()))
            .satisfies(a -> assertThat(a.getDriver()).as("check driver").isEqualTo(expected.getDriver()));
    }
}
