package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PackageDriverAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverAllPropertiesEquals(PackageDriver expected, PackageDriver actual) {
        assertPackageDriverAutoGeneratedPropertiesEquals(expected, actual);
        assertPackageDriverAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverAllUpdatablePropertiesEquals(PackageDriver expected, PackageDriver actual) {
        assertPackageDriverUpdatableFieldsEquals(expected, actual);
        assertPackageDriverUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverAutoGeneratedPropertiesEquals(PackageDriver expected, PackageDriver actual) {
        assertThat(actual)
            .as("Verify PackageDriver auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverUpdatableFieldsEquals(PackageDriver expected, PackageDriver actual) {
        assertThat(actual)
            .as("Verify PackageDriver relevant properties")
            .satisfies(a -> assertThat(a.getPackageID()).as("check packageID").isEqualTo(expected.getPackageID()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTime()).as("check time").isEqualTo(expected.getTime()))
            .satisfies(a -> assertThat(a.getBonus()).as("check bonus").isEqualTo(expected.getBonus()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverUpdatableRelationshipsEquals(PackageDriver expected, PackageDriver actual) {
        // empty method
    }
}
