package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PackageDriverAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverAllPropertiesEquals(PackageDriver expected, PackageDriver actual) {
        assertPackageDriverAutoGeneratedPropertiesEquals(expected, actual);
        assertPackageDriverAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverAllUpdatablePropertiesEquals(PackageDriver expected, PackageDriver actual) {
        assertPackageDriverUpdatableFieldsEquals(expected, actual);
        assertPackageDriverUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverAutoGeneratedPropertiesEquals(PackageDriver expected, PackageDriver actual) {
        assertThat(expected)
            .as("Verify PackageDriver auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverUpdatableFieldsEquals(PackageDriver expected, PackageDriver actual) {
        assertThat(expected)
            .as("Verify PackageDriver relevant properties")
            .satisfies(e -> assertThat(e.getPackageID()).as("check packageID").isEqualTo(actual.getPackageID()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").isEqualTo(actual.getPrice()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getTime()).as("check time").isEqualTo(actual.getTime()))
            .satisfies(e -> assertThat(e.getBonus()).as("check bonus").isEqualTo(actual.getBonus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackageDriverUpdatableRelationshipsEquals(PackageDriver expected, PackageDriver actual) {}
}
