package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportAllPropertiesEquals(Report expected, Report actual) {
        assertReportAutoGeneratedPropertiesEquals(expected, actual);
        assertReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportAllUpdatablePropertiesEquals(Report expected, Report actual) {
        assertReportUpdatableFieldsEquals(expected, actual);
        assertReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportAutoGeneratedPropertiesEquals(Report expected, Report actual) {
        assertThat(actual)
            .as("Verify Report auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportUpdatableFieldsEquals(Report expected, Report actual) {
        assertThat(actual)
            .as("Verify Report relevant properties")
            .satisfies(a -> assertThat(a.getReportID()).as("check reportID").isEqualTo(expected.getReportID()))
            .satisfies(a -> assertThat(a.getReportType()).as("check reportType").isEqualTo(expected.getReportType()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getReportStatus()).as("check reportStatus").isEqualTo(expected.getReportStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportUpdatableRelationshipsEquals(Report expected, Report actual) {
        assertThat(actual)
            .as("Verify Report relationships")
            .satisfies(a -> assertThat(a.getTrip()).as("check trip").isEqualTo(expected.getTrip()))
            .satisfies(a -> assertThat(a.getDriver()).as("check driver").isEqualTo(expected.getDriver()));
    }
}
