package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequestTripAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripAllPropertiesEquals(RequestTrip expected, RequestTrip actual) {
        assertRequestTripAutoGeneratedPropertiesEquals(expected, actual);
        assertRequestTripAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripAllUpdatablePropertiesEquals(RequestTrip expected, RequestTrip actual) {
        assertRequestTripUpdatableFieldsEquals(expected, actual);
        assertRequestTripUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripAutoGeneratedPropertiesEquals(RequestTrip expected, RequestTrip actual) {
        assertThat(actual)
            .as("Verify RequestTrip auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripUpdatableFieldsEquals(RequestTrip expected, RequestTrip actual) {
        assertThat(actual)
            .as("Verify RequestTrip relevant properties")
            .satisfies(a -> assertThat(a.getRequestTripID()).as("check requestTripID").isEqualTo(expected.getRequestTripID()))
            .satisfies(a -> assertThat(a.getStartLoca()).as("check startLoca").isEqualTo(expected.getStartLoca()))
            .satisfies(a -> assertThat(a.getEndLoca()).as("check endLoca").isEqualTo(expected.getEndLoca()))
            .satisfies(a -> assertThat(a.getAmountApproveFee()).as("check amountApproveFee").isEqualTo(expected.getAmountApproveFee()))
            .satisfies(a -> assertThat(a.getNumberofSeats()).as("check numberofSeats").isEqualTo(expected.getNumberofSeats()))
            .satisfies(a -> assertThat(a.getLuggageImg()).as("check luggageImg").isEqualTo(expected.getLuggageImg()))
            .satisfies(
                a ->
                    assertThat(a.getLuggageImgContentType())
                        .as("check luggageImg contenty type")
                        .isEqualTo(expected.getLuggageImgContentType())
            )
            .satisfies(
                a -> assertThat(a.getLuggageDescription()).as("check luggageDescription").isEqualTo(expected.getLuggageDescription())
            )
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPickUpTime()).as("check pickUpTime").isEqualTo(expected.getPickUpTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getCheckIn()).as("check checkIn").isEqualTo(expected.getCheckIn()))
            .satisfies(a -> assertThat(a.getCheckInTime()).as("check checkInTime").isEqualTo(expected.getCheckInTime()))
            .satisfies(a -> assertThat(a.getCheckOut()).as("check checkOut").isEqualTo(expected.getCheckOut()))
            .satisfies(a -> assertThat(a.getCheckOutTIme()).as("check checkOutTIme").isEqualTo(expected.getCheckOutTIme()))
            .satisfies(a -> assertThat(a.getAppliedAt()).as("check appliedAt").isEqualTo(expected.getAppliedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripUpdatableRelationshipsEquals(RequestTrip expected, RequestTrip actual) {
        assertThat(actual)
            .as("Verify RequestTrip relationships")
            .satisfies(a -> assertThat(a.getTrip()).as("check trip").isEqualTo(expected.getTrip()));
    }
}
