package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequestTripAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripAllPropertiesEquals(RequestTrip expected, RequestTrip actual) {
        assertRequestTripAutoGeneratedPropertiesEquals(expected, actual);
        assertRequestTripAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripAllUpdatablePropertiesEquals(RequestTrip expected, RequestTrip actual) {
        assertRequestTripUpdatableFieldsEquals(expected, actual);
        assertRequestTripUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripAutoGeneratedPropertiesEquals(RequestTrip expected, RequestTrip actual) {
        assertThat(expected)
            .as("Verify RequestTrip auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripUpdatableFieldsEquals(RequestTrip expected, RequestTrip actual) {
        assertThat(expected)
            .as("Verify RequestTrip relevant properties")
            .satisfies(e -> assertThat(e.getRequestTripID()).as("check requestTripID").isEqualTo(actual.getRequestTripID()))
            .satisfies(e -> assertThat(e.getStartLoca()).as("check startLoca").isEqualTo(actual.getStartLoca()))
            .satisfies(e -> assertThat(e.getEndLoca()).as("check endLoca").isEqualTo(actual.getEndLoca()))
            .satisfies(e -> assertThat(e.getAmountApproveFee()).as("check amountApproveFee").isEqualTo(actual.getAmountApproveFee()))
            .satisfies(e -> assertThat(e.getLuggageImg()).as("check luggageImg").isEqualTo(actual.getLuggageImg()))
            .satisfies(
                e ->
                    assertThat(e.getLuggageImgContentType())
                        .as("check luggageImg contenty type")
                        .isEqualTo(actual.getLuggageImgContentType())
            )
            .satisfies(e -> assertThat(e.getLuggageDescription()).as("check luggageDescription").isEqualTo(actual.getLuggageDescription()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getPickUpTime()).as("check pickUpTime").isEqualTo(actual.getPickUpTime()))
            .satisfies(e -> assertThat(e.getEndTime()).as("check endTime").isEqualTo(actual.getEndTime()))
            .satisfies(e -> assertThat(e.getCheckIn()).as("check checkIn").isEqualTo(actual.getCheckIn()))
            .satisfies(e -> assertThat(e.getCheckInTime()).as("check checkInTime").isEqualTo(actual.getCheckInTime()))
            .satisfies(e -> assertThat(e.getCheckOut()).as("check checkOut").isEqualTo(actual.getCheckOut()))
            .satisfies(e -> assertThat(e.getCheckOutTIme()).as("check checkOutTIme").isEqualTo(actual.getCheckOutTIme()))
            .satisfies(e -> assertThat(e.getAppliedAt()).as("check appliedAt").isEqualTo(actual.getAppliedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestTripUpdatableRelationshipsEquals(RequestTrip expected, RequestTrip actual) {
        assertThat(expected)
            .as("Verify RequestTrip relationships")
            .satisfies(e -> assertThat(e.getTrip()).as("check trip").isEqualTo(actual.getTrip()));
    }
}
