package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SendingAplicationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationAllPropertiesEquals(SendingAplication expected, SendingAplication actual) {
        assertSendingAplicationAutoGeneratedPropertiesEquals(expected, actual);
        assertSendingAplicationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationAllUpdatablePropertiesEquals(SendingAplication expected, SendingAplication actual) {
        assertSendingAplicationUpdatableFieldsEquals(expected, actual);
        assertSendingAplicationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationAutoGeneratedPropertiesEquals(SendingAplication expected, SendingAplication actual) {
        assertThat(expected)
            .as("Verify SendingAplication auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationUpdatableFieldsEquals(SendingAplication expected, SendingAplication actual) {
        assertThat(expected)
            .as("Verify SendingAplication relevant properties")
            .satisfies(e -> assertThat(e.getApliID()).as("check apliID").isEqualTo(actual.getApliID()))
            .satisfies(
                e -> assertThat(e.getSendApplicationType()).as("check sendApplicationType").isEqualTo(actual.getSendApplicationType())
            )
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()))
            .satisfies(e -> assertThat(e.getImg()).as("check img").isEqualTo(actual.getImg()))
            .satisfies(e -> assertThat(e.getImgContentType()).as("check img contenty type").isEqualTo(actual.getImgContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationUpdatableRelationshipsEquals(SendingAplication expected, SendingAplication actual) {}
}
