package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SendingAplicationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationAllPropertiesEquals(SendingAplication expected, SendingAplication actual) {
        assertSendingAplicationAutoGeneratedPropertiesEquals(expected, actual);
        assertSendingAplicationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationAllUpdatablePropertiesEquals(SendingAplication expected, SendingAplication actual) {
        assertSendingAplicationUpdatableFieldsEquals(expected, actual);
        assertSendingAplicationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationAutoGeneratedPropertiesEquals(SendingAplication expected, SendingAplication actual) {
        assertThat(actual)
            .as("Verify SendingAplication auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationUpdatableFieldsEquals(SendingAplication expected, SendingAplication actual) {
        assertThat(actual)
            .as("Verify SendingAplication relevant properties")
            .satisfies(a -> assertThat(a.getApliID()).as("check apliID").isEqualTo(expected.getApliID()))
            .satisfies(
                a -> assertThat(a.getSendApplicationType()).as("check sendApplicationType").isEqualTo(expected.getSendApplicationType())
            )
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getImg()).as("check img").isEqualTo(expected.getImg()))
            .satisfies(a -> assertThat(a.getImgContentType()).as("check img contenty type").isEqualTo(expected.getImgContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendingAplicationUpdatableRelationshipsEquals(SendingAplication expected, SendingAplication actual) {
        // empty method
    }
}
