package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletAllPropertiesEquals(SystemWallet expected, SystemWallet actual) {
        assertSystemWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletAllUpdatablePropertiesEquals(SystemWallet expected, SystemWallet actual) {
        assertSystemWalletUpdatableFieldsEquals(expected, actual);
        assertSystemWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletAutoGeneratedPropertiesEquals(SystemWallet expected, SystemWallet actual) {
        assertThat(expected)
            .as("Verify SystemWallet auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletUpdatableFieldsEquals(SystemWallet expected, SystemWallet actual) {
        assertThat(expected)
            .as("Verify SystemWallet relevant properties")
            .satisfies(e -> assertThat(e.getSystemWalletID()).as("check systemWalletID").isEqualTo(actual.getSystemWalletID()))
            .satisfies(e -> assertThat(e.getBefore()).as("check before").isEqualTo(actual.getBefore()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getCurrent()).as("check current").isEqualTo(actual.getCurrent()))
            .satisfies(e -> assertThat(e.getBlockAmount()).as("check blockAmount").isEqualTo(actual.getBlockAmount()))
            .satisfies(e -> assertThat(e.getMobifyDate()).as("check mobifyDate").isEqualTo(actual.getMobifyDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletUpdatableRelationshipsEquals(SystemWallet expected, SystemWallet actual) {}
}
