package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemTempWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletAllPropertiesEquals(SystemTempWallet expected, SystemTempWallet actual) {
        assertSystemTempWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemTempWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletAllUpdatablePropertiesEquals(SystemTempWallet expected, SystemTempWallet actual) {
        assertSystemTempWalletUpdatableFieldsEquals(expected, actual);
        assertSystemTempWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletAutoGeneratedPropertiesEquals(SystemTempWallet expected, SystemTempWallet actual) {
        assertThat(expected)
            .as("Verify SystemTempWallet auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletUpdatableFieldsEquals(SystemTempWallet expected, SystemTempWallet actual) {
        assertThat(expected)
            .as("Verify SystemTempWallet relevant properties")
            .satisfies(e -> assertThat(e.getSystemWalletID()).as("check systemWalletID").isEqualTo(actual.getSystemWalletID()))
            .satisfies(e -> assertThat(e.getBefore()).as("check before").isEqualTo(actual.getBefore()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getCurrent()).as("check current").isEqualTo(actual.getCurrent()))
            .satisfies(e -> assertThat(e.getMobifyDate()).as("check mobifyDate").isEqualTo(actual.getMobifyDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletUpdatableRelationshipsEquals(SystemTempWallet expected, SystemTempWallet actual) {}
}
