package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletAllPropertiesEquals(SystemWallet expected, SystemWallet actual) {
        assertSystemWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletAllUpdatablePropertiesEquals(SystemWallet expected, SystemWallet actual) {
        assertSystemWalletUpdatableFieldsEquals(expected, actual);
        assertSystemWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletAutoGeneratedPropertiesEquals(SystemWallet expected, SystemWallet actual) {
        assertThat(actual)
            .as("Verify SystemWallet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletUpdatableFieldsEquals(SystemWallet expected, SystemWallet actual) {
        assertThat(actual)
            .as("Verify SystemWallet relevant properties")
            .satisfies(a -> assertThat(a.getSystemWalletID()).as("check systemWalletID").isEqualTo(expected.getSystemWalletID()))
            .satisfies(a -> assertThat(a.getBefore()).as("check before").isEqualTo(expected.getBefore()))
            .satisfies(a -> assertThat(a.getAmount()).as("check amount").isEqualTo(expected.getAmount()))
            .satisfies(a -> assertThat(a.getCurrent()).as("check current").isEqualTo(expected.getCurrent()))
            .satisfies(a -> assertThat(a.getBlockAmount()).as("check blockAmount").isEqualTo(expected.getBlockAmount()))
            .satisfies(a -> assertThat(a.getMobifyDate()).as("check mobifyDate").isEqualTo(expected.getMobifyDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemWalletUpdatableRelationshipsEquals(SystemWallet expected, SystemWallet actual) {
        // empty method
    }
}
