package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemTempWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletAllPropertiesEquals(SystemTempWallet expected, SystemTempWallet actual) {
        assertSystemTempWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemTempWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletAllUpdatablePropertiesEquals(SystemTempWallet expected, SystemTempWallet actual) {
        assertSystemTempWalletUpdatableFieldsEquals(expected, actual);
        assertSystemTempWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletAutoGeneratedPropertiesEquals(SystemTempWallet expected, SystemTempWallet actual) {
        assertThat(actual)
            .as("Verify SystemTempWallet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletUpdatableFieldsEquals(SystemTempWallet expected, SystemTempWallet actual) {
        assertThat(actual)
            .as("Verify SystemTempWallet relevant properties")
            .satisfies(a -> assertThat(a.getSystemWalletID()).as("check systemWalletID").isEqualTo(expected.getSystemWalletID()))
            .satisfies(a -> assertThat(a.getBefore()).as("check before").isEqualTo(expected.getBefore()))
            .satisfies(a -> assertThat(a.getAmount()).as("check amount").isEqualTo(expected.getAmount()))
            .satisfies(a -> assertThat(a.getCurrent()).as("check current").isEqualTo(expected.getCurrent()))
            .satisfies(a -> assertThat(a.getMobifyDate()).as("check mobifyDate").isEqualTo(expected.getMobifyDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemTempWalletUpdatableRelationshipsEquals(SystemTempWallet expected, SystemTempWallet actual) {
        // empty method
    }
}
