package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TripStopLocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationAllPropertiesEquals(TripStopLocation expected, TripStopLocation actual) {
        assertTripStopLocationAutoGeneratedPropertiesEquals(expected, actual);
        assertTripStopLocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationAllUpdatablePropertiesEquals(TripStopLocation expected, TripStopLocation actual) {
        assertTripStopLocationUpdatableFieldsEquals(expected, actual);
        assertTripStopLocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationAutoGeneratedPropertiesEquals(TripStopLocation expected, TripStopLocation actual) {
        assertThat(expected)
            .as("Verify TripStopLocation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationUpdatableFieldsEquals(TripStopLocation expected, TripStopLocation actual) {
        assertThat(expected)
            .as("Verify TripStopLocation relevant properties")
            .satisfies(e -> assertThat(e.getStopLocaID()).as("check stopLocaID").isEqualTo(actual.getStopLocaID()))
            .satisfies(e -> assertThat(e.getStopLoca()).as("check stopLoca").isEqualTo(actual.getStopLoca()))
            .satisfies(e -> assertThat(e.getStopLocaTime()).as("check stopLocaTime").isEqualTo(actual.getStopLocaTime()))
            .satisfies(e -> assertThat(e.getStopLocaStatus()).as("check stopLocaStatus").isEqualTo(actual.getStopLocaStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationUpdatableRelationshipsEquals(TripStopLocation expected, TripStopLocation actual) {
        assertThat(expected)
            .as("Verify TripStopLocation relationships")
            .satisfies(e -> assertThat(e.getTrip()).as("check trip").isEqualTo(actual.getTrip()));
    }
}
