package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TripAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripAllPropertiesEquals(Trip expected, Trip actual) {
        assertTripAutoGeneratedPropertiesEquals(expected, actual);
        assertTripAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripAllUpdatablePropertiesEquals(Trip expected, Trip actual) {
        assertTripUpdatableFieldsEquals(expected, actual);
        assertTripUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripAutoGeneratedPropertiesEquals(Trip expected, Trip actual) {
        assertThat(expected)
            .as("Verify Trip auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripUpdatableFieldsEquals(Trip expected, Trip actual) {
        assertThat(expected)
            .as("Verify Trip relevant properties")
            .satisfies(e -> assertThat(e.getTripID()).as("check tripID").isEqualTo(actual.getTripID()))
            .satisfies(e -> assertThat(e.getTripImg()).as("check tripImg").isEqualTo(actual.getTripImg()))
            .satisfies(
                e -> assertThat(e.getTripImgContentType()).as("check tripImg contenty type").isEqualTo(actual.getTripImgContentType())
            )
            .satisfies(e -> assertThat(e.getPricePerSeat()).as("check pricePerSeat").isEqualTo(actual.getPricePerSeat()))
            .satisfies(e -> assertThat(e.getMaxSeat()).as("check maxSeat").isEqualTo(actual.getMaxSeat()))
            .satisfies(e -> assertThat(e.getStartDate()).as("check startDate").isEqualTo(actual.getStartDate()))
            .satisfies(e -> assertThat(e.getEndDate()).as("check endDate").isEqualTo(actual.getEndDate()))
            .satisfies(e -> assertThat(e.getStartLocation()).as("check startLocation").isEqualTo(actual.getStartLocation()))
            .satisfies(e -> assertThat(e.getEndLocation()).as("check endLocation").isEqualTo(actual.getEndLocation()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCondition()).as("check condition").isEqualTo(actual.getCondition()))
            .satisfies(e -> assertThat(e.getCancelReason()).as("check cancelReason").isEqualTo(actual.getCancelReason()))
            .satisfies(e -> assertThat(e.getTripStatus()).as("check tripStatus").isEqualTo(actual.getTripStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripUpdatableRelationshipsEquals(Trip expected, Trip actual) {
        assertThat(expected)
            .as("Verify Trip relationships")
            .satisfies(e -> assertThat(e.getDriver()).as("check driver").isEqualTo(actual.getDriver()));
    }
}
