package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TripStopLocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationAllPropertiesEquals(TripStopLocation expected, TripStopLocation actual) {
        assertTripStopLocationAutoGeneratedPropertiesEquals(expected, actual);
        assertTripStopLocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationAllUpdatablePropertiesEquals(TripStopLocation expected, TripStopLocation actual) {
        assertTripStopLocationUpdatableFieldsEquals(expected, actual);
        assertTripStopLocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationAutoGeneratedPropertiesEquals(TripStopLocation expected, TripStopLocation actual) {
        assertThat(actual)
            .as("Verify TripStopLocation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationUpdatableFieldsEquals(TripStopLocation expected, TripStopLocation actual) {
        assertThat(actual)
            .as("Verify TripStopLocation relevant properties")
            .satisfies(a -> assertThat(a.getStopLocaID()).as("check stopLocaID").isEqualTo(expected.getStopLocaID()))
            .satisfies(a -> assertThat(a.getStopLoca()).as("check stopLoca").isEqualTo(expected.getStopLoca()))
            .satisfies(a -> assertThat(a.getStoplocaPosition()).as("check stoplocaPosition").isEqualTo(expected.getStoplocaPosition()))
            .satisfies(a -> assertThat(a.getEstimatedTime()).as("check estimatedTime").isEqualTo(expected.getEstimatedTime()))
            .satisfies(a -> assertThat(a.getEstimatedKM()).as("check estimatedKM").isEqualTo(expected.getEstimatedKM()))
            .satisfies(a -> assertThat(a.getStopLocaTime()).as("check stopLocaTime").isEqualTo(expected.getStopLocaTime()))
            .satisfies(a -> assertThat(a.getStopLocaStatus()).as("check stopLocaStatus").isEqualTo(expected.getStopLocaStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStopLocationUpdatableRelationshipsEquals(TripStopLocation expected, TripStopLocation actual) {
        assertThat(actual)
            .as("Verify TripStopLocation relationships")
            .satisfies(a -> assertThat(a.getTrip()).as("check trip").isEqualTo(expected.getTrip()));
    }
}
