package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TripAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripAllPropertiesEquals(Trip expected, Trip actual) {
        assertTripAutoGeneratedPropertiesEquals(expected, actual);
        assertTripAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripAllUpdatablePropertiesEquals(Trip expected, Trip actual) {
        assertTripUpdatableFieldsEquals(expected, actual);
        assertTripUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripAutoGeneratedPropertiesEquals(Trip expected, Trip actual) {
        assertThat(actual)
            .as("Verify Trip auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripUpdatableFieldsEquals(Trip expected, Trip actual) {
        assertThat(actual)
            .as("Verify Trip relevant properties")
            .satisfies(a -> assertThat(a.getTripID()).as("check tripID").isEqualTo(expected.getTripID()))
            .satisfies(a -> assertThat(a.getTripImg()).as("check tripImg").isEqualTo(expected.getTripImg()))
            .satisfies(
                a -> assertThat(a.getTripImgContentType()).as("check tripImg contenty type").isEqualTo(expected.getTripImgContentType())
            )
            .satisfies(a -> assertThat(a.getPricePerSeat()).as("check pricePerSeat").isEqualTo(expected.getPricePerSeat()))
            .satisfies(a -> assertThat(a.getMaxSeat()).as("check maxSeat").isEqualTo(expected.getMaxSeat()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getCurrentSeat()).as("check currentSeat").isEqualTo(expected.getCurrentSeat()))
            .satisfies(a -> assertThat(a.getStartLocation()).as("check startLocation").isEqualTo(expected.getStartLocation()))
            .satisfies(a -> assertThat(a.getEndLocation()).as("check endLocation").isEqualTo(expected.getEndLocation()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCondition()).as("check condition").isEqualTo(expected.getCondition()))
            .satisfies(a -> assertThat(a.getCancelReason()).as("check cancelReason").isEqualTo(expected.getCancelReason()))
            .satisfies(a -> assertThat(a.getTripStatus()).as("check tripStatus").isEqualTo(expected.getTripStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripUpdatableRelationshipsEquals(Trip expected, Trip actual) {
        assertThat(actual)
            .as("Verify Trip relationships")
            .satisfies(a -> assertThat(a.getVehicle()).as("check vehicle").isEqualTo(expected.getVehicle()))
            .satisfies(a -> assertThat(a.getDriver()).as("check driver").isEqualTo(expected.getDriver()));
    }
}
