package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailAllPropertiesEquals(UserDetail expected, UserDetail actual) {
        assertUserDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailAllUpdatablePropertiesEquals(UserDetail expected, UserDetail actual) {
        assertUserDetailUpdatableFieldsEquals(expected, actual);
        assertUserDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailAutoGeneratedPropertiesEquals(UserDetail expected, UserDetail actual) {
        assertThat(expected)
            .as("Verify UserDetail auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailUpdatableFieldsEquals(UserDetail expected, UserDetail actual) {
        assertThat(expected)
            .as("Verify UserDetail relevant properties")
            .satisfies(e -> assertThat(e.getAppUserDetail()).as("check appUserDetail").isEqualTo(actual.getAppUserDetail()))
            .satisfies(e -> assertThat(e.getUserimage()).as("check userimage").isEqualTo(actual.getUserimage()))
            .satisfies(
                e -> assertThat(e.getUserimageContentType()).as("check userimage contenty type").isEqualTo(actual.getUserimageContentType())
            )
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()))
            .satisfies(e -> assertThat(e.getGender()).as("check gender").isEqualTo(actual.getGender()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailUpdatableRelationshipsEquals(UserDetail expected, UserDetail actual) {}
}
