package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletAllPropertiesEquals(UserWallet expected, UserWallet actual) {
        assertUserWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertUserWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletAllUpdatablePropertiesEquals(UserWallet expected, UserWallet actual) {
        assertUserWalletUpdatableFieldsEquals(expected, actual);
        assertUserWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletAutoGeneratedPropertiesEquals(UserWallet expected, UserWallet actual) {
        assertThat(expected)
            .as("Verify UserWallet auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletUpdatableFieldsEquals(UserWallet expected, UserWallet actual) {
        assertThat(expected)
            .as("Verify UserWallet relevant properties")
            .satisfies(e -> assertThat(e.getUserWallet()).as("check userWallet").isEqualTo(actual.getUserWallet()))
            .satisfies(e -> assertThat(e.getBefore()).as("check before").isEqualTo(actual.getBefore()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getCurrent()).as("check current").isEqualTo(actual.getCurrent()))
            .satisfies(e -> assertThat(e.getMobifyDate()).as("check mobifyDate").isEqualTo(actual.getMobifyDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletUpdatableRelationshipsEquals(UserWallet expected, UserWallet actual) {}
}
