package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletAllPropertiesEquals(UserWallet expected, UserWallet actual) {
        assertUserWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertUserWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletAllUpdatablePropertiesEquals(UserWallet expected, UserWallet actual) {
        assertUserWalletUpdatableFieldsEquals(expected, actual);
        assertUserWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletAutoGeneratedPropertiesEquals(UserWallet expected, UserWallet actual) {
        assertThat(actual)
            .as("Verify UserWallet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletUpdatableFieldsEquals(UserWallet expected, UserWallet actual) {
        assertThat(actual)
            .as("Verify UserWallet relevant properties")
            .satisfies(a -> assertThat(a.getUserWallet()).as("check userWallet").isEqualTo(expected.getUserWallet()))
            .satisfies(a -> assertThat(a.getBefore()).as("check before").isEqualTo(expected.getBefore()))
            .satisfies(a -> assertThat(a.getAmount()).as("check amount").isEqualTo(expected.getAmount()))
            .satisfies(a -> assertThat(a.getCurrent()).as("check current").isEqualTo(expected.getCurrent()))
            .satisfies(a -> assertThat(a.getMobifyDate()).as("check mobifyDate").isEqualTo(expected.getMobifyDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserWalletUpdatableRelationshipsEquals(UserWallet expected, UserWallet actual) {
        // empty method
    }
}
