package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehicleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAllPropertiesEquals(Vehicle expected, Vehicle actual) {
        assertVehicleAutoGeneratedPropertiesEquals(expected, actual);
        assertVehicleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAllUpdatablePropertiesEquals(Vehicle expected, Vehicle actual) {
        assertVehicleUpdatableFieldsEquals(expected, actual);
        assertVehicleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAutoGeneratedPropertiesEquals(Vehicle expected, Vehicle actual) {
        assertThat(expected)
            .as("Verify Vehicle auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleUpdatableFieldsEquals(Vehicle expected, Vehicle actual) {
        assertThat(expected)
            .as("Verify Vehicle relevant properties")
            .satisfies(e -> assertThat(e.getVehicleID()).as("check vehicleID").isEqualTo(actual.getVehicleID()))
            .satisfies(e -> assertThat(e.getVehicleType()).as("check vehicleType").isEqualTo(actual.getVehicleType()))
            .satisfies(e -> assertThat(e.getVehicleImage()).as("check vehicleImage").isEqualTo(actual.getVehicleImage()))
            .satisfies(
                e ->
                    assertThat(e.getVehicleImageContentType())
                        .as("check vehicleImage contenty type")
                        .isEqualTo(actual.getVehicleImageContentType())
            )
            .satisfies(e -> assertThat(e.getCarregistration()).as("check carregistration").isEqualTo(actual.getCarregistration()))
            .satisfies(
                e ->
                    assertThat(e.getCarregistrationContentType())
                        .as("check carregistration contenty type")
                        .isEqualTo(actual.getCarregistrationContentType())
            )
            .satisfies(
                e ->
                    assertThat(e.getVehicleInspectionCertificate())
                        .as("check vehicleInspectionCertificate")
                        .isEqualTo(actual.getVehicleInspectionCertificate())
            )
            .satisfies(
                e ->
                    assertThat(e.getVehicleInspectionCertificateContentType())
                        .as("check vehicleInspectionCertificate contenty type")
                        .isEqualTo(actual.getVehicleInspectionCertificateContentType())
            )
            .satisfies(e -> assertThat(e.getVehicleNumber()).as("check vehicleNumber").isEqualTo(actual.getVehicleNumber()))
            .satisfies(e -> assertThat(e.getNumberOfSeats()).as("check numberOfSeats").isEqualTo(actual.getNumberOfSeats()))
            .satisfies(e -> assertThat(e.getVehicleColor()).as("check vehicleColor").isEqualTo(actual.getVehicleColor()))
            .satisfies(e -> assertThat(e.getVehicleBrand()).as("check vehicleBrand").isEqualTo(actual.getVehicleBrand()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleUpdatableRelationshipsEquals(Vehicle expected, Vehicle actual) {
        assertThat(expected)
            .as("Verify Vehicle relationships")
            .satisfies(e -> assertThat(e.getDriver()).as("check driver").isEqualTo(actual.getDriver()));
    }
}
