package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehicleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAllPropertiesEquals(Vehicle expected, Vehicle actual) {
        assertVehicleAutoGeneratedPropertiesEquals(expected, actual);
        assertVehicleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAllUpdatablePropertiesEquals(Vehicle expected, Vehicle actual) {
        assertVehicleUpdatableFieldsEquals(expected, actual);
        assertVehicleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAutoGeneratedPropertiesEquals(Vehicle expected, Vehicle actual) {
        assertThat(actual)
            .as("Verify Vehicle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleUpdatableFieldsEquals(Vehicle expected, Vehicle actual) {
        assertThat(actual)
            .as("Verify Vehicle relevant properties")
            .satisfies(a -> assertThat(a.getVehicleID()).as("check vehicleID").isEqualTo(expected.getVehicleID()))
            .satisfies(a -> assertThat(a.getVehicleType()).as("check vehicleType").isEqualTo(expected.getVehicleType()))
            .satisfies(a -> assertThat(a.getVehicleImage()).as("check vehicleImage").isEqualTo(expected.getVehicleImage()))
            .satisfies(
                a ->
                    assertThat(a.getVehicleImageContentType())
                        .as("check vehicleImage contenty type")
                        .isEqualTo(expected.getVehicleImageContentType())
            )
            .satisfies(a -> assertThat(a.getCarregistration()).as("check carregistration").isEqualTo(expected.getCarregistration()))
            .satisfies(
                a ->
                    assertThat(a.getCarregistrationContentType())
                        .as("check carregistration contenty type")
                        .isEqualTo(expected.getCarregistrationContentType())
            )
            .satisfies(
                a ->
                    assertThat(a.getVehicleInspectionCertificate())
                        .as("check vehicleInspectionCertificate")
                        .isEqualTo(expected.getVehicleInspectionCertificate())
            )
            .satisfies(
                a ->
                    assertThat(a.getVehicleInspectionCertificateContentType())
                        .as("check vehicleInspectionCertificate contenty type")
                        .isEqualTo(expected.getVehicleInspectionCertificateContentType())
            )
            .satisfies(a -> assertThat(a.getCarInsurance()).as("check carInsurance").isEqualTo(expected.getCarInsurance()))
            .satisfies(
                a ->
                    assertThat(a.getCarInsuranceContentType())
                        .as("check carInsurance contenty type")
                        .isEqualTo(expected.getCarInsuranceContentType())
            )
            .satisfies(a -> assertThat(a.getVehicleNumber()).as("check vehicleNumber").isEqualTo(expected.getVehicleNumber()))
            .satisfies(a -> assertThat(a.getNumberOfSeats()).as("check numberOfSeats").isEqualTo(expected.getNumberOfSeats()))
            .satisfies(a -> assertThat(a.getVehicleColor()).as("check vehicleColor").isEqualTo(expected.getVehicleColor()))
            .satisfies(a -> assertThat(a.getVehicleBrand()).as("check vehicleBrand").isEqualTo(expected.getVehicleBrand()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleUpdatableRelationshipsEquals(Vehicle expected, Vehicle actual) {
        assertThat(actual)
            .as("Verify Vehicle relationships")
            .satisfies(a -> assertThat(a.getDriver()).as("check driver").isEqualTo(expected.getDriver()));
    }
}
