package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WalletTransactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionAllPropertiesEquals(WalletTransaction expected, WalletTransaction actual) {
        assertWalletTransactionAutoGeneratedPropertiesEquals(expected, actual);
        assertWalletTransactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionAllUpdatablePropertiesEquals(WalletTransaction expected, WalletTransaction actual) {
        assertWalletTransactionUpdatableFieldsEquals(expected, actual);
        assertWalletTransactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionAutoGeneratedPropertiesEquals(WalletTransaction expected, WalletTransaction actual) {
        assertThat(actual)
            .as("Verify WalletTransaction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionUpdatableFieldsEquals(WalletTransaction expected, WalletTransaction actual) {
        assertThat(actual)
            .as("Verify WalletTransaction relevant properties")
            .satisfies(a -> assertThat(a.getTransID()).as("check transID").isEqualTo(expected.getTransID()))
            .satisfies(a -> assertThat(a.getAmount()).as("check amount").isEqualTo(expected.getAmount()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getWalletType()).as("check walletType").isEqualTo(expected.getWalletType()))
            .satisfies(a -> assertThat(a.getTransStatus()).as("check transStatus").isEqualTo(expected.getTransStatus()))
            .satisfies(
                a ->
                    assertThat(a.getTransactionThirdPartyID())
                        .as("check transactionThirdPartyID")
                        .isEqualTo(expected.getTransactionThirdPartyID())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionUpdatableRelationshipsEquals(WalletTransaction expected, WalletTransaction actual) {
        assertThat(actual)
            .as("Verify WalletTransaction relationships")
            .satisfies(a -> assertThat(a.getSystemWallet()).as("check systemWallet").isEqualTo(expected.getSystemWallet()))
            .satisfies(a -> assertThat(a.getPayment()).as("check payment").isEqualTo(expected.getPayment()))
            .satisfies(a -> assertThat(a.getUserWallet()).as("check userWallet").isEqualTo(expected.getUserWallet()))
            .satisfies(a -> assertThat(a.getSystemTempWallet()).as("check systemTempWallet").isEqualTo(expected.getSystemTempWallet()));
    }
}
