package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WalletDepositAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletDepositAllPropertiesEquals(WalletDeposit expected, WalletDeposit actual) {
        assertWalletDepositAutoGeneratedPropertiesEquals(expected, actual);
        assertWalletDepositAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletDepositAllUpdatablePropertiesEquals(WalletDeposit expected, WalletDeposit actual) {
        assertWalletDepositUpdatableFieldsEquals(expected, actual);
        assertWalletDepositUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletDepositAutoGeneratedPropertiesEquals(WalletDeposit expected, WalletDeposit actual) {
        assertThat(actual)
            .as("Verify WalletDeposit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletDepositUpdatableFieldsEquals(WalletDeposit expected, WalletDeposit actual) {
        assertThat(actual)
            .as("Verify WalletDeposit relevant properties")
            .satisfies(a -> assertThat(a.getBankNumber()).as("check bankNumber").isEqualTo(expected.getBankNumber()))
            .satisfies(a -> assertThat(a.getNameOfBank()).as("check nameOfBank").isEqualTo(expected.getNameOfBank()))
            .satisfies(a -> assertThat(a.getBank()).as("check bank").isEqualTo(expected.getBank()))
            .satisfies(a -> assertThat(a.getAmount()).as("check amount").isEqualTo(expected.getAmount()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletDepositUpdatableRelationshipsEquals(WalletDeposit expected, WalletDeposit actual) {
        assertThat(actual)
            .as("Verify WalletDeposit relationships")
            .satisfies(a -> assertThat(a.getUserWallet()).as("check userWallet").isEqualTo(expected.getUserWallet()));
    }
}
