package strip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WalletTransactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionAllPropertiesEquals(WalletTransaction expected, WalletTransaction actual) {
        assertWalletTransactionAutoGeneratedPropertiesEquals(expected, actual);
        assertWalletTransactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionAllUpdatablePropertiesEquals(WalletTransaction expected, WalletTransaction actual) {
        assertWalletTransactionUpdatableFieldsEquals(expected, actual);
        assertWalletTransactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionAutoGeneratedPropertiesEquals(WalletTransaction expected, WalletTransaction actual) {
        assertThat(expected)
            .as("Verify WalletTransaction auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionUpdatableFieldsEquals(WalletTransaction expected, WalletTransaction actual) {
        assertThat(expected)
            .as("Verify WalletTransaction relevant properties")
            .satisfies(e -> assertThat(e.getTransID()).as("check transID").isEqualTo(actual.getTransID()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getDate()).as("check date").isEqualTo(actual.getDate()))
            .satisfies(e -> assertThat(e.getWalletType()).as("check walletType").isEqualTo(actual.getWalletType()))
            .satisfies(e -> assertThat(e.getTransStatus()).as("check transStatus").isEqualTo(actual.getTransStatus()))
            .satisfies(
                e ->
                    assertThat(e.getTransactionThirdPartyID())
                        .as("check transactionThirdPartyID")
                        .isEqualTo(actual.getTransactionThirdPartyID())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionUpdatableRelationshipsEquals(WalletTransaction expected, WalletTransaction actual) {
        assertThat(expected)
            .as("Verify WalletTransaction relationships")
            .satisfies(e -> assertThat(e.getSystemWallet()).as("check systemWallet").isEqualTo(actual.getSystemWallet()))
            .satisfies(e -> assertThat(e.getPayment()).as("check payment").isEqualTo(actual.getPayment()))
            .satisfies(e -> assertThat(e.getUserWallet()).as("check userWallet").isEqualTo(actual.getUserWallet()))
            .satisfies(e -> assertThat(e.getSystemTempWallet()).as("check systemTempWallet").isEqualTo(actual.getSystemTempWallet()));
    }
}
